---
- hosts: localhost
  name: Set up Fedora for development

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - files:
            - "{{ playbook_dir }}/config.yml"
          skip: true

  roles:
    - role: webarchitect609.jet_brains_toolbox
      become: true

  tasks:
    - name: Add docker repository
      become: true
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/fedora/docker-ce.repo
        dest: /etc/yum.repos.d/
        mode: 0644

    - name: Ensure dnf packages are installed
      become: true
      ansible.builtin.dnf:
        name: "{{ dnf_installed_packages }}"

    - name: Ensure flatpak packages are installed
      community.general.flatpak:
        name: "{{ flatpak_installed_packages }}"

    - name: Ensure pip packages are installed
      ansible.builtin.pip:
        name: "{{ pip_installed_packages }}"

    - name: Ensure docker service is started and enabled
      become: true
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Configure git
      community.general.git_config:
        name: "{{ item.name }}"
        scope: "{{ item.scope }}"
        value: "{{ item.value }}"
      loop: "{{ git_configs }}"

    - name: Ensure ~/.bashrc.d exists
      ansible.builtin.file:
        path: ~/.bashrc.d
        state: directory
        mode: 0750

    - name: Add git info to bash prompt
      ansible.builtin.copy:
        content: |
          . /usr/share/git-core/contrib/completion/git-prompt.sh
          export PS1='[\u@\h \W$(declare -F __git_ps1 &>/dev/null && __git_ps1 " (%s)")]\$ '
        dest: ~/.bashrc.d/add-git-info-to-prompt.sh
        mode: 0640
