---
- hosts: localhost
  name: Set up Fedora for development

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include configuration.
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - "{{ playbook_dir }}/config.yml"
          skip: true

  roles:
    - role: webarchitect609.jet_brains_toolbox
      become: true

  tasks:
    - name: Ensure dnf packages are installed
      become: true
      dnf:
        name:
          - gnome-tweaks
          - gnome-extensions-app
          - gnome-shell-extension-dash-to-dock
          - gnome-shell-extension-system-monitor-applet
          - git
          - java-11-openjdk-headless
          - golang
          - python3
          - python3-pip

    - name: Ensure flatpak packages are installed
      community.general.flatpak:
        name:
          - com.sublimetext.three
          - com.spotify.Client

    - name: Ensure ansible is installed
      pip:
        name: ansible

    - name: Configure git
      community.general.git_config:
        name: "{{ item.name }}"
        scope: "{{ item.scope }}"
        value: "{{ item.value }}"
      loop: "{{ git_configs }}"
