---
- hosts: localhost
  name: Set up Fedora for development

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - files:
            - "{{ playbook_dir }}/config.yml"
          skip: true

  roles:
    - role: webarchitect609.jet_brains_toolbox
      become: true

  tasks:
    - name: Ensure dnf packages are installed
      become: true
      ansible.builtin.dnf:
        name:
          - gnome-tweaks
          - gnome-extensions-app
          - gnome-shell-extension-dash-to-dock
          - gnome-shell-extension-system-monitor-applet
          - git
          - java-11-openjdk-headless
          - golang
          - python3
          - python3-pip

    - name: Ensure flatpak packages are installed
      community.general.flatpak:
        name:
          - com.sublimetext.three
          - com.spotify.Client

    - name: Ensure ansible is installed
      ansible.builtin.pip:
        name: ansible

    - name: Configure git
      community.general.git_config:
        name: "{{ item.name }}"
        scope: "{{ item.scope }}"
        value: "{{ item.value }}"
      loop: "{{ git_configs }}"

    - name: Ensure ~/.bashrc.d exists
      ansible.builtin.file:
        path: ~/.bashrc.d
        state: directory
        mode: 0750

    - name: Add git info to bash prompt
      ansible.builtin.copy:
        content: |
          . /usr/share/git-core/contrib/completion/git-prompt.sh
          export PS1='[\u@\h \W$(declare -F __git_ps1 &>/dev/null && __git_ps1 " (%s)")]\$ '
        dest: ~/.bashrc.d/add-git-info-to-prompt.sh
        mode: 0640
